package Biblioteca;

import Imágenes.Convertidor;
import Imágenes.Editor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

public class VentanaPrincipal extends javax.swing.JFrame {

    public static ListaSimple BaseDeDatos = new ListaSimple();
    public static Nodo ContenedorCategorías;
    public static Nodo ContenedorFotografías;
    public static ListaDobleE contenedorCategoríasLista;
    public static ListaCDobleE contenedorFotografíasLista;
    public static int i;
    public static int j;
    public static String[] nombresCategorías;
    public static String[] nombreFotos;
    public static String nombreUsuarioIngresado;
    public static File[] fotoFile;
    public static byte[] fotosBytes;
    public static Nodo nodo;

    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        irBiblioteca = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        irConvertidor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("USAC VIEWER");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Usuario:");

        irBiblioteca.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        irBiblioteca.setText("INGRESAR A BIBLIOTECA");
        irBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irBibliotecaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("MENÚ");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("INGRESAR A EDITOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        irConvertidor.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        irConvertidor.setText("INGRESAR A CONVERTIDOR");
        irConvertidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irConvertidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(irBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(nombreUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(irConvertidor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel3)))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(68, 68, 68)
                        .addComponent(irBiblioteca)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(irConvertidor)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irBibliotecaActionPerformed
        if (nombreUsuario.getText() == null || nombreUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese al menos un carácter.", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            nombreUsuarioIngresado = nombreUsuario.getText();
            ContenedorCategorías = (Nodo) BaseDeDatos.find(nombreUsuarioIngresado);
            contenedorCategoríasLista = (ListaDobleE) ContenedorCategorías.Contenido;
            i = contenedorCategoríasLista.getSize();
            nombresCategorías = new String[i];

            nombreFotos = new String[j];

            int j = 0;
            Nodo aux1 = contenedorCategoríasLista.cabecera;
            while (j < contenedorCategoríasLista.tamaño) {
                nombresCategorías[j] = aux1.Contenido.nombre;
                aux1 = aux1.getSiguiente();
                j++;
            }

            Biblioteca B = new Biblioteca();
            B.setVisible(true);
            B.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_irBibliotecaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Editor B = new Editor();
        B.setVisible(true);
        B.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Abrir
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            FileInputStream abrir = new FileInputStream("BaseDeDatos.ser");
            ObjectInputStream escribir = new ObjectInputStream(abrir);
            BaseDeDatos = (ListaSimple) escribir.readObject();
            escribir.close();
            abrir.close();
        } catch (IOException i) {
            BaseDeDatos = new ListaSimple();

        } catch (ClassNotFoundException c) {
            BaseDeDatos = new ListaSimple();
        }
    }//GEN-LAST:event_formWindowOpened

    //Cerrar
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            FileOutputStream guardar = new FileOutputStream("BaseDeDatos.ser");
            ObjectOutputStream escribir = new ObjectOutputStream(guardar);
            escribir.writeObject(BaseDeDatos);
            escribir.close();
            guardar.close();
        } catch (IOException i) {
            i.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void irConvertidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irConvertidorActionPerformed
        Convertidor B = new Convertidor();
        B.setVisible(true);
        B.setLocationRelativeTo(null);
    }//GEN-LAST:event_irConvertidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaPrincipal ventana = new VentanaPrincipal();

                // Calcular las coordenadas para centrar el JFrame en la pantalla
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                int w = ventana.getSize().width;
                int h = ventana.getSize().height;
                int x = (dim.width - w) / 2;
                int y = (dim.height - h) / 2;

                // Establecer la posición del JFrame
                ventana.setLocation(x, y);

                // Mostrar el JFrame
                ventana.setVisible(true);

            }
        });

        //Almacenamiento
        BaseDeDatos.add(new ListaDobleE("Ejemplo"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton irBiblioteca;
    private javax.swing.JButton irConvertidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
